### ISSUE TITLE
android

### ISSUE THREAD

**Issue by ghost** [LJ147/Awesome-WeChat#5]
公众号名称：终端研发部
类别：android，Java
推荐理由：「终端研发部」走在前技术领域的最前沿，打造一个最受欢迎的学习渠道，带你一起升华技术，展示一个不一样的自我
公众号微信（可选） ：codeGoogler
公众号二维码图片链接（可选）：http://upload-images.jianshu.io/upload_images/4614633-8af7afbca8ae9de9.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

**Comment by ghost** [comment]
终端研发部

**Comment by LJ147** [comment]
感谢推荐，已经更新～ @androidstarjacksky
